debug: false # Use this to help with debugging, this will happily spit out your keys.. so watch out posting logs anywhere
metrics: :9100 # Address for a prometheus listener
interface:
  address: "<your ip address>"
  private_key: "<your private key>"
  dns: # dns servers to be used
    - "1.1.1.1"
    - "1.0.0.1"
peer:
  - public_key: "<public key>"
    endpoint: "<end point ip address>:51820"
    allowedip: "0.0.0.0/0" # What addresses is it allowed to have, or rather what should get routed through it
    keep_alive: 60
proxy:
  http:
    addr: ":8080" # Expose a http proxy on this port
  socks5:
    addr: ":8888" # Expose a socks5 proxy on this port